---
- hosts: all
  become: true

  tasks:

    - name: install packages
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools

    - name: add key GPG
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

    - name: add repository docker
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present

    - name: installa docker
        apt:
          name: "{{item}}"
          state: latest
          update_cache: yes
        loop:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: assicurati che docker sia attivo
        service:
          name: docker
          state: started
          enabled: yes

    - name: Install Docker Module for Python
        pip:
          name: docker
