version: '3.3'
services:

  post_db:
    container_name: db
    env_file:
      - .env
    image: mongo:${VERSION_DB}
    volumes:
      - ./data:/data/db
    networks:
      back_net:
        aliases:
          - comment_db

  ui:
    container_name: ui
    env_file:
      - .env
    image: ${USERNAME}/ui:${VERSION_UI}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net

  post:
    container_name: post
    env_file:
      - .env
    image: ${USERNAME}/post:${VERSION_POST}
    networks:
      - front_net
      - back_net

  comment:
    container_name: comment
    env_file:
      - .env
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    networks:
      - front_net
      - back_net

  prometheus:
    container_name: prometheus
    image: ${USERNAME}/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net

  node-exporter:
    container_name: node_exporter
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    ports:
      - 9100:9100
    networks:
      - front_net
      - back_net

  mongo-exporter:
    container_name: db_exporter
    image: noenv/mongo-exporter
    ports:
      - 9123:9123
    command:
      - '--web.listen-address=:9123'
      - '--mongodb.uri=mongodb://post_db:27017'
    networks:
      - front_net
      - back_net

  black-box:
    container_name: black-box
    image: ${USERNAME}/black-box
    ports:
      - 9115:9115
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    networks:
      - front_net
      - back_net


volumes:
  data:
  prometheus_data:

networks:
  back_net:
    driver: bridge
  front_net:
    driver: bridge
