---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     namespace: default
     name: mongo-pvc
  gcePersistentDisk:
    fsType: "ext4"
    pdName: k8s
